#include<bits/stdc++.h>
using namespace std;

int main(){

/*copy value from v2 
if no value are given than it will be 0 by default . if give value than that will be showed  */

   
/*     case 1
  int a[6]= {1,2,3,4,5,6};
     vector<int> v(a, a+6);
 */

             
      vector<int> v = {2,10,3};
      for (int i = 0; i <v.size(); i++)
      {
        cout << v[i] << " ";
      }
      cout << v.size() << endl;
      return 0;

      


}